### ISSUE TITLE
Cant Change Config Settings in Magento 2

### ISSUE THREAD

**Issue by Greenbebiz** [ebizmarts/magento2-magemonkey#16]
When I try to disable this extension or change API credentials, I get a infinite spinning css animation.  How do i restore default values to this MageMonkey extension?

**Comment by Greenbebiz** [comment]
we updated the magento 2 extension but the configuration won't save the same issue is still occurring

**Comment by Santiagoebizmarts** [comment]
This seems to be working properly on the latest release. Please update the extension.

Kind Regards.
