### ISSUE TITLE
Not working with Guest customer

### ISSUE THREAD

**Issue by sunilit42** [ebizmarts/magento2-magemonkey#17]
Hello,

If I subscribe newsletter from my account then it is working fine.

But i am not registered user and I try to register my email  id then it is not working.

I checked the code as well no plugin develop this.
beforeSubscribeCustomerById()=> it is use for only register user.

you need to create Aftersubscribe()  for the guest user.

**Comment by dio5** [comment]
I can confirm this. Unless I'm missing something, I couldn't find where this is happening, nor can find anything about cronjobs happening related to syncing.

**Comment by MauroNigrele** [comment]
I can confirm this too, no guest subscription.

**Comment by bjoern-quast** [comment]
I can confim this.
The only API call seems to be in afterSubscribeCustomerById(), which is only called when a registered, logged-in user subscribes.

**Comment by maderlock** [comment]
Starting to put M2 production sites live. The ability to have non-logged-in customers sign up is pretty fundamental. Any estimate of when this feature might be included?

**Comment by benoitcanton** [comment]
Hey guys,

I got the same issues but updated MageMonkey from 3.0.3 to 3.0.5 and now it is working. Hope it helps.

**Comment by Santiagoebizmarts** [comment]
Hi guys, Guest subscription is working in the latest release.
Thanks @benoitcanton for letting everyone know.
