### ISSUE TITLE
Registration error with empty Customer Fields Mapping

### ISSUE THREAD

**Issue by jzahedieh** [ebizmarts/magento2-magemonkey#19]
### Situation - How did you get there?

Try to register to newsletter when Customer Fields Mapping is yet to be configured / empty.

### Problem - What went wrong?

Exception is thrown:

    Warning: Invalid argument supplied for foreach() in /var/www/html/vendor/ebizmarts/magento2-magemonkey/Helper/Data.php on line 84

### Possible solution - How should it be?

Add check for failed serialization and return empty array instead, I am creating a PR for this.

**Comment by Santiagoebizmarts** [comment]
This have been fixed in the latest release. Please update the extension and if you find it is not we can reopen this issue.
