### ISSUE TITLE
Customer registration bug

### ISSUE THREAD

**Issue by peccopi** [ebizmarts/magento2-magemonkey#22]
After create customer Account the message "Customer could not saved" returned.

But the Customer is successfully created and can find in backend.

Mage Monkey Module is configured other modules actually not.

> main.CRITICAL: Exception message: The message should be an instance of \Zend_Mail
> Trace: #0 /home/myvintag/subdomains/demo/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(99): Emizentech\CustomSmtp\Model\Transport->__construct(Object(Ebizmarts\Mandrill\Model\Message), Object(Emizentech\CustomSmtp\Helper\Data))
> #1 /home/myvintag/subdomains/demo/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Emizentech\\Cust...', Array)
> #2 /home/myvintag/subdomains/demo/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Emizentech\\Cust...', Array)
> #3 /home/myvintag/subdomains/demo/vendor/magento/framework/Mail/TransportInterfaceFactory.php(50): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
> #4 /home/myvintag/subdomains/demo/vendor/magento/framework/Mail/Template/TransportBuilder.php(228): Magento\Framework\Mail\TransportInterfaceFactory->create(Array)
> #5 /home/myvintag/subdomains/demo/vendor/magento/module-customer/Model/AccountManagement.php(925): Magento\Framework\Mail\Template\TransportBuilder->getTransport()
> #6 /home/myvintag/subdomains/demo/vendor/magento/module-customer/Model/AccountManagement.php(836): Magento\Customer\Model\AccountManagement->sendEmailTemplate(Object(Magento\Customer\Model\Data\Customer), 'customer/create...', 'customer/create...', Array, 1)
> #7 /home/myvintag/subdomains/demo/vendor/magento/module-customer/Model/AccountManagement.php(587): Magento\Customer\Model\AccountManagement->sendNewAccountEmail(Object(Magento\Customer\Model\Data\Customer), 'registered', NULL, 1)
> #8 /home/myvintag/subdomains/demo/vendor/magento/module-customer/Model/AccountManagement.php(547): Magento\Customer\Model\AccountManagement->sendEmailConfirmation(Object(Magento\Customer\Model\Data\Customer), NULL)
> #9 /home/myvintag/subdomains/demo/var/generation/Magento/Customer/Model/AccountManagement/Interceptor.php(141): Magento\Customer\Model\AccountManagement->createAccountWithPasswordHash(Object(Magento\Customer\Model\Data\Customer), '2e006533e691b8b...', NULL)
> #10 /home/myvintag/subdomains/demo/vendor/magento/module-customer/Model/AccountManagement.php(484): Magento\Customer\Model\AccountManagement\Interceptor->createAccountWithPasswordHash(Object(Magento\Customer\Model\Data\Customer), '2e006533e691b8b...', NULL)
> #11 /home/myvintag/subdomains/demo/var/generation/Magento/Customer/Model/AccountManagement/Interceptor.php(128): Magento\Customer\Model\AccountManagement->createAccount(Object(Magento\Customer\Model\Data\Customer), '23039003', NULL)
> #12 /home/myvintag/subdomains/demo/vendor/magento/module-customer/Controller/Account/CreatePost.php(233): Magento\Customer\Model\AccountManagement\Interceptor->createAccount(Object(Magento\Customer\Model\Data\Customer), '23039003', NULL)
> #13 /home/myvintag/subdomains/demo/var/generation/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(24): Magento\Customer\Controller\Account\CreatePost->execute()
> #14 /home/myvintag/subdomains/demo/vendor/magento/framework/App/Action/Action.php(102): Magento\Customer\Controller\Account\CreatePost\Interceptor->execute()
> #15 [internal function]: Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
> #16 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
> #17 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent('dispatch', Array)
> #18 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'designLoader')
> #19 /home/myvintag/subdomains/demo/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #20 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #21 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
> #22 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'customer-app-ac...')
> #23 /home/myvintag/subdomains/demo/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #24 [internal function]: Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #25 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
> #26 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'storeCheck')
> #27 /home/myvintag/subdomains/demo/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #28 [internal function]: Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #29 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
> #30 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'contextPlugin')
> #31 /home/myvintag/subdomains/demo/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #32 [internal function]: Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #33 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
> #34 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'customer_accoun...')
> #35 /home/myvintag/subdomains/demo/vendor/magento/module-customer/Controller/Plugin/Account.php(60): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #36 [internal function]: Magento\Customer\Controller\Plugin\Account->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #37 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
> #38 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'tax-app-action-...')
> #39 /home/myvintag/subdomains/demo/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #40 [internal function]: Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #41 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
> #42 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'weee-app-action...')
> #43 /home/myvintag/subdomains/demo/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #44 [internal function]: Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #45 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
> #46 /home/myvintag/subdomains/demo/var/generation/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(39): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins('dispatch', Array, Array)
> #47 /home/myvintag/subdomains/demo/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #48 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
> #49 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
> #50 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
> #51 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
> #52 /home/myvintag/subdomains/demo/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(89): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #53 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #54 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
> #55 /home/myvintag/subdomains/demo/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
> #56 /home/myvintag/subdomains/demo/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))

**Comment by Santiagoebizmarts** [comment]
Hello @peccopi,
What version of the module do you have installed? With the latest version this is not happening to me. Please test it and let me know to reopen this issue.

**Comment by peccopi** [comment]
Hi @Santiagoebizmarts,

Sorry for late answer. I still try to use your module, but i got the same problem with an another fresh install of m 2.1.1. I try the module fom the ebismart store and the last dev version. API Key ia also entered. You can see the Problem in my system.log:

> [2016-09-05 09:49:57] main.CRITICAL: Exception message: Notice: Trying to get property of non-object in /home/vnmoebel/domains/vnmoebel.de/app/code/Ebizmarts/Mandrill/Model/Transport.php on line 84
> Trace: #0 /home/vnmoebel/domains/vnmoebel.de/app/code/Ebizmarts/Mandrill/Model/Transport.php(84): Magento\Framework\App\ErrorHandler->handler(8, 'Trying to get p...', '/home/vnmoebel/...', 84, Array)
> #1 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(146): Ebizmarts\Mandrill\Model\Transport->sendMessage()
> #2 /home/vnmoebel/domains/vnmoebel.de/var/generation/Ebizmarts/Mandrill/Model/Transport/Interceptor.php(26): Ebizmarts\Mandrill\Model\Transport\Interceptor->___callPlugins('sendMessage', Array, Array)
> #3 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Model/EmailNotification.php(239): Ebizmarts\Mandrill\Model\Transport\Interceptor->sendMessage()
> #4 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Model/EmailNotification.php(363): Magento\Customer\Model\EmailNotification->sendEmailTemplate(Object(Magento\Customer\Model\Data\Customer), 'customer/create...', 'customer/create...', Array, 1)
> #5 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Model/AccountManagement.php(777): Magento\Customer\Model\EmailNotification->newAccount(Object(Magento\Customer\Model\Data\Customer), 'registered', 'http://demo.vnm...', 1)
> #6 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Model/AccountManagement.php(737): Magento\Customer\Model\AccountManagement->sendEmailConfirmation(Object(Magento\Customer\Model\Data\Customer), 'http://demo.vnm...')
> #7 /home/vnmoebel/domains/vnmoebel.de/var/generation/Magento/Customer/Model/AccountManagement/Interceptor.php(141): Magento\Customer\Model\AccountManagement->createAccountWithPasswordHash(Object(Magento\Customer\Model\Data\Customer), '19ff2c910c8b303...', 'http://demo.vnm...')
> #8 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Model/AccountManagement.php(662): Magento\Customer\Model\AccountManagement\Interceptor->createAccountWithPasswordHash(Object(Magento\Customer\Model\Data\Customer), '19ff2c910c8b303...', 'http://demo.vnm...')
> #9 /home/vnmoebel/domains/vnmoebel.de/var/generation/Magento/Customer/Model/AccountManagement/Interceptor.php(128): Magento\Customer\Model\AccountManagement->createAccount(Object(Magento\Customer\Model\Data\Customer), 'Test123!', 'http://demo.vnm...')
> #10 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Controller/Account/CreatePost.php(277): Magento\Customer\Model\AccountManagement\Interceptor->createAccount(Object(Magento\Customer\Model\Data\Customer), 'Test123!', 'http://demo.vnm...')
> #11 /home/vnmoebel/domains/vnmoebel.de/var/generation/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(24): Magento\Customer\Controller\Account\CreatePost->execute()
> #12 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/App/Action/Action.php(102): Magento\Customer\Controller\Account\CreatePost\Interceptor->execute()
> #13 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
> #14 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent('dispatch', Array)
> #15 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'storeCheck')
> #16 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #17 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #18 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'contextPlugin')
> #19 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #20 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #21 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'customer-app-ac...')
> #22 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #23 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #24 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'weee-app-action...')
> #25 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #26 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #27 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'tax-app-action-...')
> #28 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #29 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #30 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'customer_accoun...')
> #31 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-customer/Controller/Plugin/Account.php(60): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #32 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Customer\Controller\Plugin\Account->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #33 /home/vnmoebel/domains/vnmoebel.de/var/generation/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(39): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins('dispatch', Array, Array)
> #34 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #35 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
> #36 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
> #37 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
> #38 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #39 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #40 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
> #41 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #42 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #43 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
> #44 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #45 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #46 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
> #47 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #48 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #49 /home/vnmoebel/domains/vnmoebel.de/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
> #50 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #51 /home/vnmoebel/domains/vnmoebel.de/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
> #52 /home/vnmoebel/domains/vnmoebel.de/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
> #53 {main} [] []
>

I hope you can help me

**Comment by Santiagoebizmarts** [comment]
Hello,

This is really an issue for the [Mandrill](https://github.com/ebizmarts/magento2-mandrill) module. Please make sure you have the latest version available there. You can see this at [Releases section](https://github.com/ebizmarts/magento2-mandrill/releases).
I'm closing this ticket but will review this problem anyways. Please create an issue at [Mandrill Issues section](https://github.com/ebizmarts/magento2-mandrill/issues) informing wether you have the latest version available there or not and remind us of the error message if possible.

Regards.
