### ISSUE TITLE
Fatal error: Cannot use Monolog\Logger as Logger

### ISSUE THREAD

**Issue by MhorGonzales** [ebizmarts/magento2-magemonkey#23]
I'm getting this error every time I go to MageMonkey admin.

Fatal error: Cannot use Monolog\Logger as Logger because the name is already in use in /Users/user/Sites/classic-spirit/vendor/ebizmarts/magento2-magemonkey/Model/Logger/Handler.php on line 14

from
`use Monolog\Logger;`

to
`use Monolog;`

**Comment by Santiagoebizmarts** [comment]
This has been solved in the latest release.
