### ISSUE TITLE
Fatal error: Cannot use Monolog\Logger as Logger because the name is already in use.

### ISSUE THREAD

**Issue by MhorGonzales** [ebizmarts/magento2-magemonkey#24]
After installing version **3.0.6**, the error below still exist after going to Stores->Configuration->MageMonkey->MageMonkey.

_Fatal error: Cannot use Monolog\Logger as Logger because the name is already in use in /Users/user/Sites/classic-spirit/vendor/ebizmarts/magento2-magemonkey/Model/Logger/Handler.php on line 14_

## Suggested Fix
Either you adjust the use namespace (line 14)

`use Monolog;`

or change line 28 to:

`protected $loggerType = \Monolog\Logger:INFO;`

Thanks.

**Comment by rashidio** [comment]
ebizmarts, just do it! Thanks!

**Comment by maderlock** [comment]
Such a simple fix! Thanks, @MhorGonzales - Ebizmarts don't pay a lot of attention to these free extensions so it might be best to make your own fork.
