### ISSUE TITLE
Magemonkey double mails issue on Magento 2

### ISSUE THREAD

**Issue by nmallepally** [ebizmarts/magento2-magemonkey#26]
After configuring mage monkey on magento 2. customers receives two emails after subscribing newsletter. one from mail chimp(success) and one from magento(to confirm), how can we disable magento mails from sending. As it is misleading for customers.

**Comment by gonzaloebiz** [comment]
Try with Need to confirm in 'No'
Go to Stores->Configuration->Customers->Newsletter and set Need to Confirm to 'No'

Best

**Comment by nmallepally** [comment]
@gonzaloebiz it stops the mail chimp confirmation mail but not magento 2 mail.
we need mailchimp success mail rather than magento 2.

**Comment by gonzaloebiz** [comment]
Try adding this lines
Afetr this line https://github.com/ebizmarts/magento2-magemonkey/blob/develop/Model/Plugin/Subscriber.php#L95
and after this line https://github.com/ebizmarts/magento2-magemonkey/blob/develop/Model/Plugin/Subscriber.php#L129
put this line:
$subscriber->setImportMode(true);

Let us know if this fix your issue

Best

**Comment by nmallepally** [comment]
Hi,
It stopped sending mails, when need to confirm set to yes and no as well.

**Comment by gonzaloebiz** [comment]
Both mails? (magento and mailchimp) or only magento mails?

**Comment by nmallepally** [comment]
It sends only magento mails, does not send mail chimp mail. @gonzaloebiz

**Comment by nmallepally** [comment]
@gonzaloebiz @centerax  Hi guys, Any update??. we want to use mailchimp newsletter success confirmation mail rather than magento. can you please suggest a fix.

**Comment by maderlock** [comment]
This post on the Ebizmarts forum from July shows that they are only doing bug fixes for these modules: https://ebizmarts.com/forums/topics/view/22529 so I would not hold your breath for any additional features.
