### ISSUE TITLE
Unsubscribe not working in Magneto 2

### ISSUE THREAD

**Issue by MhorGonzales** [ebizmarts/magento2-magemonkey#27]
After subscribing as guest. I tried to go to Marketing->Newsletter Subscribers and tried to unsubscribe (via Magento 2 admin). 

Expected Result:
- Unsubscribe e-mail should be received
- Unsubscribed e-mail removed from MailChimp list

Actual Result:
- Unsubscribe e-mail should be received (Success)
- Unsubscribed e-mail is **STILL** on the list (Fail)

**Comment by Santiagoebizmarts** [comment]
@MhorGonzales Hello,

Are you sure you are testing this with the latest version? I think you might have an old MageMonkey.

**Comment by MhorGonzales** [comment]
Hi @Santiagoebizmarts,

Yes, in fact I was using 3.0.7. Replication is to subscribe as guest user then unsubscribe via Magento Admin (expecting Subscriber->beforeUnsubscribe() to trigger).

Guest subscription works on 3.0.7 so that's another evidence that I'm using the latest 😄

**Comment by Santiagoebizmarts** [comment]
@MhorGonzales I will review this and get back to you with more information.
Thanks for the feedback.
