### ISSUE TITLE
Get list return only 10 results

### ISSUE THREAD

**Issue by benoitcanton** [ebizmarts/magento2-magemonkey#28]
Hi guys,

Looks like by default MailChimp GET/lists request returns only 10 results that can be an issue.
In my case we have 22 lists and the new one created wasn't showing up in the select input of the admin page.

Figured out that there is a "count" parameters for this request, to quickly fix it I simply added:
`$host .= '?count=50';` in ebizmarts/magento2-magemonkey/Model/MCAPI.php before the return of the getHost function.

Can you fix that in a future release ?

**Comment by MhorGonzales** [comment]
Experienced the same issue. I had 13 list on my sandbox account and "General Subscription" drop-down only displays 10 records.

**Comment by Santiagoebizmarts** [comment]
Will be merged into Master before next release.
