### ISSUE TITLE
Magento 2.0.9 stops sending E-Mails after Magemonkey Installation

### ISSUE THREAD

**Issue by flipflap** [ebizmarts/magento2-magemonkey#29]
Hi 

Since I tried to install magemonkey I don't get any sales E-Mails from my Magenoto.

I connected Magemonkey to Mailchimp already. But now I disabled Magemonkey, Mandrill, Abandonned Cart and Autoresponder. But Magento still can't send any E-Mails.

Is it possible that the problem is Magemonkey? If yes how can I remove it.

Thanks

**Comment by flipflap** [comment]
I disabled now all ebizmarts moduls by command line and now Magento can send emails again. It took me hours of debugging...

**Comment by Santiagoebizmarts** [comment]
Hello @flipflap ,

This problem will be solved by removing the Mandrill module.
Just run this command in your Magento root folder:
**php bin/magento module:disable Ebizmarts_AutoResponser Ebizmarts_AbandonedCart Ebizmarts_Mandrill**

Regards,
