### ISSUE TITLE
Can't subscribe registered user

### ISSUE THREAD

**Issue by Serzhik** [ebizmarts/magento2-magemonkey#30]
When I try to register user, I get an error.
It raised at app\code\Ebizmarts\MageMonkey\Model\MCAPI.php, function callServer

https://github.com/ebizmarts/magento2-magemonkey/blob/develop/Model/MCAPI.php#L80

```
$host: us12.api.mailchimp.com/3.0/lists/**********/members 
$key: ***************************** (my key)
```

https://github.com/ebizmarts/magento2-magemonkey/blob/develop/Model/MCAPI.php#L123

`$data: stdClass Object ( [type] => http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ [title] => Resource Not Found [status] => 404 [detail] => The requested resource could not be found. [instance] => )`

**Comment by Serzhik** [comment]
Please, look at https://github.com/ebizmarts/magento2-magemonkey/commit/cdaa97e6a1456e852175341ba896ffa5d2e1e64a

**Comment by Santiagoebizmarts** [comment]
Hello @Serzhik,

A new version is coming tomorrow. Please test it since it should solve this.
