### ISSUE TITLE
Opt-In Emails Not Working Correctly

### ISSUE THREAD

**Issue by crtsl** [ebizmarts/magento2-magemonkey#31]
I am using Magento 2.1.0 with MageMonkey 3.0.7. With opt-in confirmation enabled the MailChimp confirmation emails are not being sent correctly. When subscribing to the newsletter from the Magento signup in the footer, an email confirmation gets sent from Magento with a link to click to confirm. That link does not add the subscriber to the MailChimp list. Another email then gets sent from MailChimp for confirmation and the link in that email works. It would be best to only have one email sent that works.

More info is in [this thread](http://ebizmarts.com/forums/topics/view/22626) on the MageMonkey forums.

**Comment by Santiagoebizmarts** [comment]
Hello,

Thanks for contacting us. Will test this and see how to fix it.

Regards.

**Comment by crtsl** [comment]
@Santiagoebizmarts  Any updates on this?

**Comment by Santiagoebizmarts** [comment]
Hello @crtsl,

We are releasing a new version tomorrow with this fix and others.
