### ISSUE TITLE
Support for interest groups

### ISSUE THREAD

**Issue by chrey** [ebizmarts/magento2-magemonkey#36]
### Situation - How did you get there?
Looking for the code to subscribe to multiple interest centers in Magento 2 

### Problem - What went wrong?
No code found

### Possible solution - How should it be?
Do you know when this feature will be added to the Magento 2 module ? Website still says it is supported but I think it's not. 
![selection_010](https://cloud.githubusercontent.com/assets/644773/18826186/67ab3a66-83cc-11e6-9228-f700d185f40f.png)

Thank you

**Comment by maderlock** [comment]
This post on the Ebizmarts forum from July shows that they are only doing bug fixes for these modules: https://ebizmarts.com/forums/topics/view/22529 so I would not hold your breath for any additional features (even those they have promised in the past)

**Comment by Santiagoebizmarts** [comment]
Hello @chrey 
Sorry for the delay. What @maderlock says is true. We are already working on MailChimp For Magento 2 and will not dedicate time on adding new features to MageMonkey 2.

I hope you find MailChimp for Magento suitable to your needs when it becomes available.

Regards.

**Comment by chrey** [comment]
Hi, 
Thanks for the answer. When is this new extension going to be available for Magento 2 ? Will it have the interest group feature ? 
Charlotte

**Comment by Santiagoebizmarts** [comment]
@chrey 

I want to say by the end of this year but there is no actual date established yet.

Regards.

**Comment by chrey** [comment]
Hi @Santiagoebizmarts , 
We are at the end of the year now, do you have any update on the release date of the new module  ?
Thank you 
Charlotte

**Comment by Santiagoebizmarts** [comment]
Hello,

We are currently working in a new extension for Magento 2. We are only fixing bugs for this extension at the moment.

Regards,

**Comment by chrey** [comment]
@Santiagoebizmarts,
I was talking about the new module, a few months ago, you said it should be released by the end of the year. Is it still the target ? 
Thanks

**Comment by Santiagoebizmarts** [comment]
@chrey 
Oh okay, we are still working on the new module. We should have this working in a couple months. Holidays are really busy for us so the development might slow down a bit.

Regards.

**Comment by chrey** [comment]
Hi, 
Any news on the release date ? 
Thanks
Charlotte
