### ISSUE TITLE
Warning: array_merge(): Argument #2 is not an array in vendor/ebizmarts/magento2-magemonkey/Helper/Data.php on line 116

### ISSUE THREAD

**Issue by dungnv** [ebizmarts/magento2-magemonkey#38]
got this msg after submit "Subscriber to newsletter" in grid customers
Warning: array_merge(): Argument #2 is not an array in vendor/ebizmarts/magento2-magemonkey/Helper/Data.php on line 116

**Comment by Santiagoebizmarts** [comment]
Hello @dungnv 
This looks like something that may happen only with some php versions. Please make sure you do have the latest MageMonkey version 3.0.8.
If the problem is with your php version then the commit referenced above will solve your problem.

Regards.

**Comment by ihor-sviziev** [comment]
@Santiagoebizmarts magneto 2 has minimum requirement php 5.5. 
According to php changelog - short array syntax was introduced in php 5.4: http://php.net/manual/en/migration54.new-features.php

So looks like your change has no sense.
