### ISSUE TITLE
Ebizmarts\MageMonkey\Model\MCAPI should use CurlFactory, rather than accepting a direct copy of the Curl class.

### ISSUE THREAD

**Issue by mwgamble** [ebizmarts/magento2-magemonkey#39]
https://github.com/ebizmarts/magento2-magemonkey/blob/develop/Model/MCAPI.php#L37

**Comment by Santiagoebizmarts** [comment]
Hello,

Thanks for your feedback. We are currently working on a new extension that will eventually replace MageMonkey, this means we are not improving this module at the moment. We are only working on bug fixing until we release the new one.

Regards.
