### ISSUE TITLE
TO email address change for all transnational emails

### ISSUE THREAD

**Issue by ravibhalodia** [ebizmarts/magento2-magemonkey#40]
After install and configuring mailchimp, TO email address used for every transnational emails got changed to one email address. It means, all transnational emails stopped working.

This issue happens with Mandrill module. If we are disabling Mandrill then everything work seamlessly.

**Comment by Santiagoebizmarts** [comment]
Hello,

Please read [this guidelines](https://github.com/ebizmarts/magento2-magemonkey/wiki/Issue-reporting-guidelines) to see how to create an issue with all the necessary data.
I will close this one in the meantime.

Regards.
