### ISSUE TITLE
Error during module installation 

### ISSUE THREAD

**Issue by giusecapo** [ebizmarts/magento2-magemonkey#46]
When I run the "enable (module name)".
I get this:
`Failed loading /usr/local/php70/lib/php/extensions/ioncube.so:  /usr/local/php70/lib/php/extensions/ioncube.so: undefined symbol: zend_ce_division_by_zero_error
X-Powered-By: PHP/5.6.30
Content-type: text/html; charset=UTF-8`

**Comment by gonzaloebiz** [comment]
Hi @giusecapo 

thanks for your contact.
We don't use ioncube, so the error is not related to our extension, for sure you have another extension that use it.

Best
