### ISSUE TITLE
Code lives in app/code, but can also stay in vendor

### ISSUE THREAD

**Issue by stefandoorn** [ebizmarts/magento2-magemonkey#5]
Not sure why it is moved into app/code, but most modules just live in the vendor/ folder after using the composer require functionality. Would be great to have it only in there.

**Comment by centerax** [comment]
You got a point there @stefandoorn , we will review this and make the appropriate changes.

**Comment by stefandoorn** [comment]
Great! It also applies for some other modules (AutoResponder & AbondonedCart).

**Comment by gonzaloebiz** [comment]
Are you installing the extension via composer?
If you run composer require ebizmarts/magento2-magemonkey the extension is installed in vendor folder

**Comment by stefandoorn** [comment]
Yep, did use the composer require functionality. It lives in vendor/, but for some reason also in app/code. Also reinstalled my whole application (not for this, had to do it anyway) and it happened again. The first time I used composer require, the second time just composer install as the composer.lock file was already complete and acceptable.
