### ISSUE TITLE
Magento 2.1.7

### ISSUE THREAD

**Issue by msawyers** [ebizmarts/magento2-magemonkey#51]
Hello, 

This extension disappears on magento 2.1.7 when run magento setup:upgrade 

Not compatible with Magento 2.1.7

**Comment by centerax** [comment]
@msawyers this extension will be removed soon. it will be deprecated in favor of Mailchimp for Magento 2.
Would you like access to the private beta?

**Comment by msawyers** [comment]
Yes please

**Comment by Sam-PUMP** [comment]
I would too if possible ...

Thanks!!

**Comment by gonzaloebiz** [comment]
Send an email to mailchimp@ebizmarts-desk.zendesk.com and we will send instructions for beta testers

Best
