### ISSUE TITLE
Install while installing Magento gives error

### ISSUE THREAD

**Issue by stefandoorn** [ebizmarts/magento2-magemonkey#9]
I don't have the logs unfortunately, but basically what happened today:
* In app/etc/config.php the MageMonkey module was enabled
* We ran a full Magento CLI install
* At step 10 or something, the MageMonkey installer kicks in, trying to adjust the quote table, which doesn't exist.

This leads me to think that the dependencies of the MageMonkey module should be refined. In /etc/module.xml you can define which modules need to be present, before this module can be installed/updated, etc. In there I don't see any dependencies. Basically it comes down to this part of the manual that I think is necessary: http://devdocs.magento.com/guides/v2.0/architecture/archi_perspectives/components/modules/mod_depend.html

**Comment by gonzaloebiz** [comment]
Hi @stefandoorn,

are you sure the error with quote table is with MageMonkey? The extension don't touch this table in any way

**Comment by stefandoorn** [comment]
Hm, it might be one of the other Ebizmarts then.. It was for sure one of Ebizmarts.. So it's this one, or Mandrill, or .. :) I have them all 4 installed.

**Comment by stefandoorn** [comment]
I'll close this one, it should live in here: https://github.com/ebizmarts/magento2-abandonedcart/issues/4
